#pragma once


#define WFL_ALLOC_POLICY_NED_POOLING 1
#define WFL_ALLOC_POLICY_NED 2
#define WFL_ALLOC_POLICY_STANDARD 3

#define WFL_ALLOC_POLICY WFL_ALLOC_POLICY_NED_POOLING
//#define WFL_ALLOC_POLICY WFL_ALLOC_POLICY_NED
//#define WFL_ALLOC_POLICY WFL_ALLOC_POLICY_STANDARD


#define WFL_USE_HEAP_TRACKING 1 // Heapトラッキング機能を使用


